import { Board } from "../types/interfaces";

export const mockBoards: Board[] = [
    {
        id: 1,
        title: 'Launch Campaign',
        desc: "Plan and execute the marketing campaign for Q1.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 1, title: 'Draft Marketing Plan', details: 'Create a detailed marketing plan.', status: 'to_do' },
            { id: 2, title: 'Review Budget', details: 'Ensure budget aligns with goals.', status: 'to_do' },
            { id: 3, title: 'Finalize Content', details: 'Complete the content for ads.', status: 'in_progress' },
            { id: 4, title: 'Schedule Posts', details: 'Schedule social media posts.', status: 'in_progress' },
            { id: 5, title: 'Launch Ads', details: 'Launch campaigns on platforms.', status: 'done' },
        ],
    },
    {
        id: 2,
        title: 'Team Onboarding',
        desc: "Ensure new team members are onboarded successfully.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 6, title: 'Send Welcome Email', details: 'Send an introductory email.', status: 'to_do' },
            { id: 7, title: 'Setup Accounts', details: 'Create system accounts for new hires.', status: 'to_do' },
            { id: 8, title: 'Orientation Session', details: 'Organize an orientation session.', status: 'in_progress' },
            { id: 9, title: 'Assign Mentors', details: 'Pair new hires with mentors.', status: 'done' },
        ],
    },
    {
        id: 3,
        title: 'Product Development',
        desc: "Track the progress of the new product development.",
        creator: 'User 1',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 10, title: 'Ideation', details: 'Brainstorm product ideas.', status: 'to_do' },
            { id: 11, title: 'Prototype', details: 'Develop initial prototypes.', status: 'in_progress' },
            { id: 12, title: 'Testing', details: 'Conduct product testing.', status: 'in_progress' },
            { id: 13, title: 'Launch', details: 'Launch the product.', status: 'done' },
        ],
    },
    {
        id: 4,
        title: 'Event Planning',
        desc: "Organize the upcoming corporate event.",
        creator: 'User 2',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 14, title: 'Venue Booking', details: 'Reserve the event venue.', status: 'to_do' },
            { id: 15, title: 'Catering', details: 'Arrange food and drinks.', status: 'in_progress' },
            { id: 16, title: 'Invitations', details: 'Send invites to attendees.', status: 'done' },
        ],
    },
    {
        id: 5,
        title: 'Website Redesign',
        desc: "Redesign the company website for a fresh look.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 17, title: 'Wireframe Design', details: 'Create wireframes for pages.', status: 'to_do' },
            { id: 18, title: 'UI Development', details: 'Develop front-end design.', status: 'to_do' },
            { id: 19, title: 'Testing', details: 'Test responsiveness.', status: 'in_progress' },
            { id: 20, title: 'Deploy', details: 'Deploy the new website.', status: 'done' },
        ],
    },
    {
        id: 6,
        title: 'Customer Support Optimization',
        desc: "Improve the efficiency of the support team.",
        creator: 'User 3',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 21, title: 'Hire Support Agents', details: 'Recruit additional team members.', status: 'to_do' },
            { id: 22, title: 'Update Knowledge Base', details: 'Expand FAQ section.', status: 'in_progress' },
            { id: 23, title: 'Integrate Chatbot', details: 'Add AI-based support.', status: 'done' },
        ],
    },
    {
        id: 7,
        title: 'Inventory Management System',
        desc: "Develop a robust inventory tracking system.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 24, title: 'Design Database', details: 'Create ER diagrams for inventory.', status: 'to_do' },
            { id: 25, title: 'Develop API', details: 'Implement RESTful services.', status: 'in_progress' },
            { id: 26, title: 'Integration Testing', details: 'Ensure system compatibility.', status: 'done' },
        ],
    },
    {
        id: 8,
        title: 'Social Media Campaign',
        desc: "Increase brand awareness through social platforms.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 27, title: 'Create Posts', details: 'Design engaging social media posts.', status: 'to_do' },
            { id: 28, title: 'Collaborate with Influencers', details: 'Reach out to influencers.', status: 'to_do' },
            { id: 29, title: 'Analyze Metrics', details: 'Track engagement and reach.', status: 'in_progress' },
        ],
    },
    {
        id: 9,
        title: 'App Performance Optimization',
        desc: "Enhance app speed and user experience.",
        creator: 'User 5',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 30, title: 'Code Profiling', details: 'Identify bottlenecks in code.', status: 'to_do' },
            { id: 31, title: 'Optimize Queries', details: 'Speed up database interactions.', status: 'in_progress' },
            { id: 32, title: 'Stress Testing', details: 'Evaluate app under load.', status: 'done' },
        ],
    },
    {
        id: 10,
        title: 'Employee Training Program',
        desc: "Launch a new training initiative for employees.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 33, title: 'Identify Topics', details: 'List key training areas.', status: 'to_do' },
            { id: 34, title: 'Prepare Materials', details: 'Create slides and handouts.', status: 'to_do' },
            { id: 35, title: 'Conduct Workshops', details: 'Deliver training sessions.', status: 'in_progress' },
            { id: 36, title: 'Feedback Analysis', details: 'Review participant feedback.', status: 'done' },
        ],
    },
    {
        id: 11,
        title: 'Office Relocation',
        desc: "Manage the logistics of moving to a new office space.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 37, title: 'Select New Office', details: 'Find and choose a new location.', status: 'to_do' },
            { id: 38, title: 'Hire Movers', details: 'Contract a moving company.', status: 'to_do' },
            { id: 39, title: 'Pack Office Items', details: 'Pack all office equipment and documents.', status: 'in_progress' },
            { id: 40, title: 'Setup New Office', details: 'Unpack and arrange furniture and electronics.', status: 'done' },
        ],
    },
    {
        id: 12,
        title: 'Annual Audit Preparation',
        desc: "Prepare all necessary documentation for the annual financial audit.",
        creator: 'User 7',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 41, title: 'Collect Financial Documents', details: 'Gather all invoices and receipts.', status: 'to_do' },
            { id: 42, title: 'Review Compliance', details: 'Check legal and financial compliance.', status: 'to_do' },
            { id: 43, title: 'Prepare Audit Files', details: 'Organize documents for auditors.', status: 'in_progress' },
            { id: 44, title: 'Meet with Auditors', details: 'Schedule and conduct audit meetings.', status: 'done' },
        ],
    },
    {
        id: 13,
        title: 'Health and Safety Compliance',
        desc: "Ensure all workplace health and safety regulations are met.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 45, title: 'Audit Current Safety Measures', details: 'Review existing safety protocols.', status: 'to_do' },
            { id: 46, title: 'Update Safety Training', details: 'Refresh training modules.', status: 'to_do' },
            { id: 47, title: 'Conduct Safety Drills', details: 'Practice emergency procedures.', status: 'in_progress' },
            { id: 48, title: 'File Compliance Report', details: 'Submit updated compliance documents.', status: 'done' },
        ],
    },
    {
        id: 14,
        title: 'Software Upgrade',
        desc: "Upgrade the core software systems used by the company.",
        creator: 'User 7',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 49, title: 'Evaluate New Software', details: 'Research and select software upgrades.', status: 'to_do' },
            { id: 50, title: 'Backup Existing Data', details: 'Ensure all data is backed up.', status: 'to_do' },
            { id: 51, title: 'Install New Software', details: 'Implement new software systems.', status: 'in_progress' },
            { id: 52, title: 'User Training', details: 'Train employees on new software.', status: 'done' },
        ],
    },
    {
        id: 15,
        title: 'Marketing Strategy Update',
        desc: "Revise and update the company's marketing strategy for the next quarter.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 53, title: 'Market Analysis', details: 'Conduct a detailed market study.', status: 'to_do' },
            {
                id: 54, title: 'Competitor Review', details: "Analyze competitors' marketing moves.", status: 'to_do'
            },
            { id: 55, title: 'Strategy Revision', details: 'Draft new marketing strategies.', status: 'in_progress' },
            { id: 56, title: 'Team Briefing', details: 'Inform marketing team of new strategies.', status: 'done' },
        ],
    },
    {
        id: 16,
        title: 'Corporate Wellness Program',
        desc: "Introduce a wellness program to improve employee health and satisfaction.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 57, title: 'Wellness Survey', details: 'Gather employee interest and needs.', status: 'to_do' },
            { id: 58, title: 'Program Design', details: 'Plan activities like yoga, meditation.', status: 'to_do' },
            { id: 59, title: 'Vendor Selection', details: 'Choose wellness program providers.', status: 'in_progress' },
            { id: 60, title: 'Launch Event', details: 'Organize an event to kick off the program.', status: 'done' },
        ],
    },
    {
        id: 17,
        title: 'Annual Conference Preparation',
        desc: "Organize and execute the annual company conference.",
        creator: 'User 1',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 61, title: 'Keynote Speakers', details: 'Invite and confirm speakers.', status: 'to_do' },
            { id: 62, title: 'Event Schedule', details: 'Create a detailed agenda.', status: 'to_do' },
            { id: 63, title: 'Venue Setup', details: 'Arrange for audio, visuals, and seating.', status: 'in_progress' },
            { id: 64, title: 'Pre-Event Briefing', details: 'Brief staff on event logistics.', status: 'done' },
        ],
    },
    {
        id: 18,
        title: 'Cybersecurity Enhancements',
        desc: "Improve the company's cybersecurity measures.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 65, title: 'Vulnerability Assessment', details: 'Conduct a security audit.', status: 'to_do' },
            { id: 66, title: 'Update Security Protocols', details: 'Revise current security policies.', status: 'to_do' },
            { id: 67, title: 'Employee Training', details: 'Educate staff on cybersecurity.', status: 'in_progress' },
            { id: 68, title: 'Implement New Tools', details: 'Install new security software.', status: 'done' },
        ],
    },
    {
        id: 19,
        title: 'New Product Launch',
        desc: "Coordinate all aspects of launching a new product.",
        creator: 'User 7',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 69, title: 'Product Finalization', details: 'Finalize product specs and features.', status: 'to_do' },
            { id: 70, title: 'Marketing Materials', details: 'Prepare brochures, ads, and demos.', status: 'to_do' },
            { id: 71, title: 'Media Outreach', details: 'Contact press and influencers.', status: 'in_progress' },
            { id: 72, title: 'Launch Event', details: 'Organize the product launch event.', status: 'done' },
        ],
    },
    {
        id: 20,
        title: 'Recruitment Drive',
        desc: "Streamline the hiring process for multiple new positions.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 73, title: 'Job Descriptions', details: 'Write clear job roles.', status: 'to_do' },
            { id: 74, title: 'Post Job Openings', details: 'Advertise vacancies on job sites.', status: 'to_do' },
            { id: 75, title: 'Interview Scheduling', details: 'Arrange interviews with candidates.', status: 'in_progress' },
            { id: 76, title: 'Hiring Decisions', details: 'Finalize selections and send offers.', status: 'done' },
        ],
    },
    {
        id: 21,
        title: 'Supply Chain Optimization',
        desc: "Streamline and optimize the supply chain process.",
        creator: 'User 2',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 77, title: 'Supplier Evaluation', details: 'Assess current supplier performance.', status: 'to_do' },
            { id: 78, title: 'Logistics Review', details: 'Analyze transportation costs and routes.', status: 'to_do' },
            { id: 79, title: 'Implement New Software', details: 'Introduce supply chain management software.', status: 'in_progress' },
            { id: 80, title: 'Training Staff', details: 'Train employees on new systems.', status: 'done' },
        ],
    },
    {
        id: 22,
        title: 'Environmental Sustainability Initiative',
        desc: "Implement eco-friendly practices within the company.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 81, title: 'Waste Audit', details: 'Analyze company waste output.', status: 'to_do' },
            { id: 82, title: 'Green Policy Drafting', details: 'Draft environmental policies.', status: 'to_do' },
            { id: 83, title: 'Install Recycling Bins', details: 'Set up recycling stations.', status: 'in_progress' },
            { id: 84, title: 'Educational Workshops', details: 'Conduct workshops on sustainability.', status: 'done' },
        ],
    },
    {
        id: 23,
        title: 'Customer Feedback Loop',
        desc: "Create a system to gather and act on customer feedback.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 85, title: 'Survey Design', details: 'Create customer satisfaction surveys.', status: 'to_do' },
            { id: 86, title: 'Feedback Collection', details: 'Distribute surveys across platforms.', status: 'to_do' },
            { id: 87, title: 'Data Analysis', details: 'Review and analyze feedback data.', status: 'in_progress' },
            { id: 88, title: 'Action Plan', details: 'Develop response plans based on feedback.', status: 'done' },
        ],
    },
    {
        id: 24,
        title: 'Corporate Culture Enhancement',
        desc: "Improve the company culture to boost morale and productivity.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 89, title: 'Employee Survey', details: 'Gather employee opinions on culture.', status: 'to_do' },
            { id: 90, title: 'Culture Committee', details: 'Form a committee to develop initiatives.', status: 'to_do' },
            { id: 91, title: 'Team Building Events', details: 'Organize events to improve team cohesion.', status: 'in_progress' },
            { id: 92, title: 'Recognition Programs', details: 'Implement employee recognition systems.', status: 'done' },
        ],
    },
    {
        id: 25,
        title: 'Tech Infrastructure Upgrade',
        desc: "Upgrade the IT infrastructure for better performance and security.",
        creator: 'User 2',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 93, title: 'Needs Assessment', details: 'Evaluate current IT infrastructure.', status: 'to_do' },
            { id: 94, title: 'Vendor Proposals', details: 'Request proposals for new hardware/software.', status: 'to_do' },
            { id: 95, title: 'Installation Planning', details: 'Plan the upgrade process.', status: 'in_progress' },
            { id: 96, title: 'System Testing', details: 'Test new systems post-installation.', status: 'done' },
        ],
    },
    {
        id: 26,
        title: 'Legal Compliance Review',
        desc: "Ensure all business practices comply with the latest legal standards.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 97, title: 'Regulation Update', details: 'Research new laws affecting the business.', status: 'to_do' },
            { id: 98, title: 'Policy Audit', details: 'Audit existing policies against new laws.', status: 'to_do' },
            { id: 99, title: 'Policy Revisions', details: 'Update policies to ensure compliance.', status: 'in_progress' },
            { id: 100, title: 'Staff Training', details: 'Train staff on new compliance requirements.', status: 'done' },
        ],
    },
    {
        id: 27,
        title: 'Annual Performance Reviews',
        desc: "Conduct and manage the annual employee performance evaluations.",
        creator: 'User 5',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 101, title: 'Prepare Review Forms', details: 'Update and distribute performance review forms.', status: 'to_do' },
            { id: 102, title: 'Schedule Reviews', details: 'Book times for each employee review.', status: 'to_do' },
            { id: 103, title: 'Conduct Reviews', details: 'Hold meetings to discuss performance.', status: 'in_progress' },
            { id: 104, title: 'Feedback Compilation', details: 'Compile feedback and set goals.', status: 'done' },
        ],
    },
    {
        id: 28,
        title: 'R&D Project',
        desc: "Manage a new research and development project.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 105, title: 'Project Scope Definition', details: 'Define the goals and objectives.', status: 'to_do' },
            { id: 106, title: 'Team Assembly', details: 'Recruit team members with necessary skills.', status: 'to_do' },
            { id: 107, title: 'Prototype Development', details: 'Build initial prototypes.', status: 'in_progress' },
            { id: 108, title: 'Patent Application', details: 'File for patent protection.', status: 'done' },
        ],
    },
    {
        id: 29,
        title: 'Public Relations Campaign',
        desc: "Launch a PR campaign to improve public perception.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 109, title: 'PR Strategy', details: 'Outline the campaign strategy.', status: 'to_do' },
            { id: 110, title: 'Media List', details: 'Compile a list of media contacts.', status: 'to_do' },
            { id: 111, title: 'Press Release', details: 'Draft and distribute press releases.', status: 'in_progress' },
            { id: 112, title: 'Media Monitoring', details: 'Track media coverage and adjust strategy.', status: 'done' },
        ],
    },
    {
        id: 30,
        title: 'Facility Expansion',
        desc: "Plan and execute the expansion of company facilities.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 113, title: 'Feasibility Study', details: 'Assess the need and feasibility of expansion.', status: 'to_do' },
            { id: 114, title: 'Architect Consultation', details: 'Meet with architects for design plans.', status: 'to_do' },
            { id: 115, title: 'Construction Management', details: 'Oversee construction process.', status: 'in_progress' },
            { id: 116, title: 'Facility Opening', details: 'Plan and execute opening ceremonies.', status: 'done' },
        ],
    },
    {
        id: 31,
        title: 'Corporate Training Program',
        desc: "Develop and roll out a corporate-wide training initiative.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 117, title: 'Training Needs Analysis', details: 'Identify training gaps across departments.', status: 'to_do' },
            { id: 118, title: 'Curriculum Development', details: 'Design training modules.', status: 'to_do' },
            { id: 119, title: 'Training Sessions', details: 'Schedule and conduct training.', status: 'in_progress' },
            { id: 120, title: 'Post-Training Evaluation', details: 'Evaluate the effectiveness of training.', status: 'done' },
        ],
    },
    {
        id: 32,
        title: 'International Market Entry',
        desc: "Prepare for market entry into a new country.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 121, title: 'Market Research', details: 'Study the new market environment.', status: 'to_do' },
            { id: 122, title: 'Legal Compliance', details: 'Understand local laws and regulations.', status: 'to_do' },
            { id: 123, title: 'Local Partnerships', details: 'Establish relationships with local businesses.', status: 'in_progress' },
            { id: 124, title: 'Launch Strategy', details: 'Develop a tailored market entry strategy.', status: 'done' },
        ],
    },
    {
        id: 33,
        title: 'Data Privacy Compliance',
        desc: "Ensure compliance with data protection regulations.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 125, title: 'Regulation Review', details: 'Review applicable data privacy laws.', status: 'to_do' },
            { id: 126, title: 'Data Audit', details: 'Audit current data handling practices.', status: 'to_do' },
            { id: 127, title: 'System Updates', details: 'Implement necessary security enhancements.', status: 'in_progress' },
            { id: 128, title: 'Compliance Training', details: 'Train staff on privacy protocols.', status: 'done' },
        ],
    },
    {
        id: 34,
        title: 'IT Disaster Recovery Plan',
        desc: "Develop a comprehensive disaster recovery strategy for IT systems.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 129, title: 'Risk Assessment', details: 'Identify potential IT disasters.', status: 'to_do' },
            { id: 130, title: 'Recovery Strategy', details: 'Plan recovery steps for each scenario.', status: 'to_do' },
            { id: 131, title: 'Backup System Upgrade', details: 'Enhance data backup solutions.', status: 'in_progress' },
            { id: 132, title: 'Recovery Testing', details: 'Conduct disaster recovery drills.', status: 'done' },
        ],
    },
    {
        id: 35,
        title: 'Employee Benefits Revamp',
        desc: "Revise and enhance the employee benefits package.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 133, title: 'Benefits Survey', details: 'Gather employee feedback on benefits.', status: 'to_do' },
            { id: 134, title: 'Market Research', details: 'Research competitive benefits packages.', status: 'to_do' },
            { id: 135, title: 'Benefits Proposal', details: 'Draft new benefits proposals.', status: 'in_progress' },
            { id: 136, title: 'Implementation', details: 'Roll out new benefits to employees.', status: 'done' },
        ],
    },
    {
        id: 36,
        title: 'Brand Identity Redesign',
        desc: "Redesign the company's brand identity for a modern look.",
        creator: 'User 7',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 137, title: 'Brand Audit', details: 'Evaluate current branding elements.', status: 'to_do' },
            { id: 138, title: 'Design Brief', details: 'Create a brief for the design team.', status: 'to_do' },
            { id: 139, title: 'New Logo Design', details: 'Develop new logo concepts.', status: 'in_progress' },
            { id: 140, title: 'Brand Guidelines', details: 'Establish new brand usage rules.', status: 'done' },
        ],
    },
    {
        id: 37,
        title: 'Quality Control Implementation',
        desc: "Introduce new quality control measures in production.",
        creator: 'User 5',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 141, title: 'QC Standards Review', details: 'Review existing quality standards.', status: 'to_do' },
            { id: 142, title: 'New Procedures', details: 'Develop new quality control procedures.', status: 'to_do' },
            { id: 143, title: 'Staff Training', details: 'Train staff on new QC methods.', status: 'in_progress' },
            { id: 144, title: 'Audit and Feedback', details: 'Conduct initial audits and gather feedback.', status: 'done' },
        ],
    },
    {
        id: 38,
        title: 'Corporate Anniversary Celebration',
        desc: "Plan an event to celebrate the company's founding anniversary.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 145, title: 'Theme Selection', details: 'Choose an appropriate theme for the celebration.', status: 'to_do' },
            { id: 146, title: 'Venue Booking', details: 'Secure a venue for the event.', status: 'to_do' },
            { id: 147, title: 'Event Planning', details: 'Organize entertainment and catering.', status: 'in_progress' },
            { id: 148, title: 'Anniversary Activities', details: 'Plan special activities for the day.', status: 'done' },
        ],
    },
    {
        id: 39,
        title: 'Remote Work Policy',
        desc: "Develop and implement a remote work policy.",
        creator: 'User 5',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 149, title: 'Policy Research', details: 'Research effective remote work policies.', status: 'to_do' },
            { id: 150, title: 'Draft Policy', details: 'Create a draft policy document.', status: 'to_do' },
            { id: 151, title: 'Stakeholder Feedback', details: 'Gather feedback from key stakeholders.', status: 'in_progress' },
            { id: 152, title: 'Policy Implementation', details: 'Roll out the policy company-wide.', status: 'done' },
        ],
    },
    {
        id: 40,
        title: 'Corporate Social Responsibility',
        desc: "Enhance the company's CSR initiatives.",
        creator: 'Me',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 153, title: 'CSR Audit', details: 'Review current CSR activities.', status: 'to_do' },
            { id: 154, title: 'New Initiatives', details: 'Propose new CSR programs.', status: 'to_do' },
            { id: 155, title: 'Partnership Development', details: 'Collaborate with NGOs or community groups.', status: 'in_progress' },
            { id: 156, title: 'Program Launch', details: 'Officially start new CSR projects.', status: 'done' },
        ],
    },
    {
        id: 41,
        title: 'Customer Service Training',
        desc: "Enhance customer service skills through targeted training.",
        creator: 'User 5',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 157, title: 'Training Needs Assessment', details: 'Evaluate current service levels.', status: 'to_do' },
            { id: 158, title: 'Training Curriculum', details: 'Craft customer service training modules.', status: 'to_do' },
            { id: 159, title: 'Training Sessions', details: 'Conduct training for service team.', status: 'in_progress' },
            { id: 160, title: 'Post-Training Evaluation', details: 'Assess improvements in service.', status: 'done' },
        ],
    },
    {
        id: 42,
        title: 'Budget Planning for Next Fiscal Year',
        desc: "Plan the financial budget for the upcoming fiscal year.",
        creator: 'User 7',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            {
                id: 161, title: 'Financial Review', details: "Analyze last year's financial performance.", status: 'to_do'
            },
            { id: 162, title: 'Budget Projections', details: 'Forecast expenses and revenues.', status: 'to_do' },
            { id: 163, title: 'Departmental Allocations', details: 'Allocate funds to departments.', status: 'in_progress' },
            { id: 164, title: 'Board Approval', details: 'Present budget for board approval.', status: 'done' },
        ],
    },
    {
        id: 43,
        title: 'Software Bug Tracking',
        desc: "Track and resolve software bugs in the current product.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 165, title: 'Bug Collection', details: 'Gather all reported bugs.', status: 'to_do' },
            { id: 166, title: 'Prioritization', details: 'Rank bugs by severity and impact.', status: 'to_do' },
            { id: 167, title: 'Debugging', details: 'Fix bugs in development environment.', status: 'in_progress' },
            { id: 168, title: 'Release Patch', details: 'Deploy fixes in new software release.', status: 'done' },
        ],
    },
    {
        id: 44,
        title: 'Internal Communication Upgrade',
        desc: "Improve internal communications tools and practices.",
        creator: 'User 4',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 169, title: 'Audit Current Tools', details: 'Review effectiveness of current systems.', status: 'to_do' },
            { id: 170, title: 'New Tool Selection', details: 'Choose new communication platforms.', status: 'to_do' },
            { id: 171, title: 'Implementation', details: 'Roll out new tools across the company.', status: 'in_progress' },
            { id: 172, title: 'Training & Adoption', details: 'Train staff and monitor adoption.', status: 'done' },
        ],
    },
    {
        id: 45,
        title: 'Employee Recognition Program',
        desc: "Establish a formal program to recognize employee achievements.",
        creator: 'User 6',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 173, title: 'Recognition Criteria', details: 'Define what achievements to recognize.', status: 'to_do' },
            { id: 174, title: 'Reward Types', details: 'Decide on types of rewards or recognition.', status: 'to_do' },
            { id: 175, title: 'Program Launch', details: 'Announce and start the recognition program.', status: 'in_progress' },
            { id: 176, title: 'First Award Ceremony', details: 'Hold the first recognition event.', status: 'done' },
        ],
    },
    {
        id: 46,
        title: 'Marketing Analytics Setup',
        desc: "Set up analytics for tracking marketing campaign performance.",
        creator: 'User 3',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 177, title: 'Tool Selection', details: 'Choose analytics software for marketing.', status: 'to_do' },
            { id: 178, title: 'Integration', details: 'Integrate with current marketing platforms.', status: 'to_do' },
            { id: 179, title: 'Data Collection', details: 'Start collecting data from campaigns.', status: 'in_progress' },
            { id: 180, title: 'Report Generation', details: 'Generate first set of analytics reports.', status: 'done' },
        ],
    },
    {
        id: 47,
        title: 'Annual Company Retreat',
        desc: "Organize an annual retreat for team building and strategic planning.",
        creator: 'User 2',
        columns: [
            { id: 'to_do', title: 'To Do' },
            { id: 'in_progress', title: 'In Progress' },
            { id: 'done', title: 'Done' },
        ],
        tasks: [
            { id: 181, title: 'Destination Selection', details: 'Choose retreat location.', status: 'to_do' },
            { id: 182, title: 'Agenda Planning', details: 'Plan activities and sessions.', status: 'to_do' },
            { id: 183, title: 'Logistics', details: 'Arrange travel and accommodations.', status: 'in_progress' },
            { id: 184, title: 'Retreat Execution', details: 'Execute the retreat program.', status: 'done' },
        ],
    },
];